version: '0.9'

services:

  front:
    container_name: front
    image: front:latest
    ports:
      - 8000:4173
    networks:
      - dev_net
  
  db:
    container_name: db
    image: ankane/pgvector:latest
    networks:
      - dev_net
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: server
    image: server:latest
    volumes:
      - ./data:/data/
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev_net

  gateway:
    container_name: gateway
    image: gateway:latest
    ports:
      - 8080:8080
    networks:
      - dev_net

  translator:
    container_name: translator
    image: translator:latest
    volumes:
      - /home/francisco/.cache:/root/.cache
    networks:
      - dev_net


networks:
  dev_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24